version: '3.9'

services:
  api_service:
    build: .
    container_name: currency_api_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/currency
  postgres:
    container_name: postgres
    restart: always
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "currency"

